Fix warnings due to missing return for CUTEST_UNIX__
In file included from testaes.c:7:0:
./ext/cutest.h: In function ‘test_print_in_color’:
./ext/cutest.h:146:12: error: variable ‘n’ set but not used
[-Werror=unused-but-set-variable]
     size_t n;
            ^
./ext/cutest.h: In function ‘test_print_in_color’:
./ext/cutest.h:195:1: error: control reaches end of non-void function
[-Werror=return-type]
 }
 ^